#! /bin/sh
# wm independent hotkeys
XF86AudioRaiseVolume
	pulseaudio-ctl up
XF86AudioLowerVolume
	pulseaudio-ctl down
XF86AudioMute
	pulseaudio-ctl mute
XF86MonBrightnessUp
	xbacklight -inc 10%
XF86MonBrightnessDown
	xbacklight -dec 10%
XF86AudioPlay
	mpc toggle
XF86AudioNext
	mpc next
XF86AudioPrev
	mpc prev
Print
	xfce4-screenshooter -d 1 -r -s /home/admin/Images/

# terminal emulator
super + Return
	xfce4-terminal

# File browser
super + alt + Return
	pcmanfm

# program launcher
super + space
	dmenu_run -l 0 -x 20 -y 42 -w 2520 -h 20 -fn "Droid Sans-8" -o 0.60 -nb "#181818" -nf "#d8d8d8" -sb "#585858" -sf "#7cafc2" -p ">" -q -i -class "dmenu"


# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit bspwm normally
super + alt + Escape
	bspc quit && pkill panel

#
# state/flags
#

# set the window state
super + {t,s,f}
	bspc node -t {tiled,floating,fullscreen}

# set the window state to sticky and floating
super + a
	bspc node -t floating; \
	bspc node -g sticky

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node
super + {_,shift + }c
	bspc node -f {next,prev}

# focus the next/previous desktop
super + {Left,Right}
	bspc desktop -f {prev,next}

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus or send to the given desktop
super + {_,shift + }{1-9,0,minus,equal}
	bspc {desktop -f,node -d} '^{1-9,10,11,12}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# resize tiled/floating
#

# expand the tiled space in the given direction
super + alt + {h,j,k,l}
	bspc node {@west -r -10,@south -r +10,@north -r -10,@east -r +10}

# contract the tiled space in the given direction
super + alt + shift + {h,j,k,l}
	bspc node {@east -r -10,@north -r +10,@south -r -10,@west -r +10}

# move a floating window
super + {Left,Right}

#
# pointer focus/move/resize
#

# start move/resize
super + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}

# end move/resize
super + @button{1-3}
	bspc pointer -u

# move a floating window
super + alt + {Left,Down,Up,Right}
	xdo move {-x -20,-y +20,-y -20,-x +20}

#
# Gap
#
alt + {minus,equal}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` {+,-} 2 ))
