#! /bin/sh
# Custom keys
XF86AudioRaiseVolume
	pulseaudio-ctl up
XF86AudioLowerVolume
	pulseaudio-ctl down
XF86AudioMute
	pulseaudio-ctl mute
XF86MonBrightnessUp
	xbacklight -inc 10%
XF86MonBrightnessDown
	xbacklight -dec 10%
XF86AudioPlay
	mpc toggle
XF86AudioNext
	mpc next
XF86AudioPrev
	mpc prev
Print
	xfce4-screenshooter -r -s /home/admin/Images/

#
# bspwm hotkeys
#

super + alt + Escape
	bspc quit && pkill panel

super + w
	bspc window -c

super + t
	bspc desktop -l next

super + b
	bspc desktop -B

super + {s,f}
	bspc window -t {floating,fullscreen}

super + {grave,Tab}
	bspc {window,desktop} -f last

super + apostrophe
	bspc window -s last

# to delete
super + {o,i}
	bspc control --record-history off; \
	bspc window {older,newer} -f; \
	bspc control --record-history on

# to delete
super + y
	bspc window -w last.manual

super + m
	bspc window -s biggest

super + {_,shift + }{h,j,k,l}
	bspc window -{f,s} {left,down,up,right}

super + {_,shift + }c
	bspc window -f {next,prev}

super + {comma,period}
	bspc desktop -C {backward,forward}

super + bracket{left,right}
	bspc desktop -f {prev,next}

super + {Left,Right}
	bspc desktop -f {prev,next}

super + ctrl + {h,j,k,l}
	bspc window -p {left,down,up,right}

super + ctrl + {_,shift + }space
	bspc {window -p cancel,desktop -c}

super + alt + {h,j,k,l}
	bspc window -e {left -10,down +10,up -10,right +10}

super + alt + shift + {h,j,k,l}
	bspc window -e {right -10,up +10,down -10,left +10}

super + ctrl + {1-9}
	bspc window -r 0.{1-9}

super + {_,shift + }{1-9,0}
	bspc {desktop -f,window -d} ^{1-9,10}

~button1
	bspc pointer -g focus

super + button1
	; bspc pointer -g move

super + shift + button1
	; bspc pointer -g resize_corner

super + !button{1-3}
    bspc pointer -t %i %i

super + @button{1-3}
	bspc pointer -u

alt + {minus,equal}
    bspc config -d focused window_gap $((`bspc config -d focused window_gap` {+,-} 2 ))

#
# wm independent hotkeys
#

super + Return
	xfce4-terminal

super + space
    dmenu_run -l 0 -x 0 -y 42 -w 1920 -h 28 -fn "Droid Sans-10" -nb "#181818" -nf "#d8d8d8" -sb "#585858" -sf "#7cafc2" -p ">" -q -i

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd
