#! /bin/sh
# Panel parser
########################

########################
# SOURCE CONFIG
. $(dirname $0)/lemonbar_config


num_mon=$(bspc query -M | wc -l)
while read -r line ; do
	case $line in
		C*)
			# clock output
			clock="$PADDING${line#?}$PADDING"
			;;

		I*)
			# IP output
			ip="%{A:gksudo openvpnSwitch Netherlands &:}$PADDING${line#?}$PADDING%{A}"
			;;
		T*)
			# xtitle output
			title=${line#?}
			title="%{B$COLOR_TITLE_BG}$PADDING${title:0:$TITLE_MAX_LENGTH}$PADDING%{B-}$PADDING"
			;;

		V*)
			# alsa volume
			volume="%{A4:pulseaudio-ctl up:}%{A5:pulseaudio-ctl down:}$PADDING${line#?}$PADDING%{A}%{A}"
			;;

		L*)
			# player
			playing="%{B$COLOR_STATUS_BG}%{F$COLOR_STATUS_FG}$PADDING${line#?}$PADDING%{F-}%{B-}"
			;;

		D*)
			# cpu temp
			systemp="$PADDING$ICON_TEMP${line#?}$PADDING"
			;;

		U*)
			# cpu temp
			updates="%{A:xfce4-terminal --command='yaourt -Suua' --drop-down &:}$PADDING$ICON_PAC${line#?}$PADDING%{A}"
			;;

		X*)
			# conky array
			IFS=':'
			sys_arr=( $line )

			########
			#CPU
			cpu=${sys_arr[0]}
			cpu=${cpu:1:4}
			if [ $cpu -gt $CPU_WARN_LEVEL ]; then
				cpu=$(urgent $cpu%)
			else 
				cpu=$cpu%
			fi
			cpu="$PADDING$ICON_CPU$cpu$PADDING"
			########
			#RAM

			ram="$PADDING$ICON_RAM${sys_arr[1]}$PADDING"
			########
			#HDDs
			root=${sys_arr[2]}
			if [ $root -gt $DISK_SPACE_WARN_LEVEL ]; then
				root=$(urgent $root%)
			else 
				root=$root%
			fi
			win=${sys_arr[4]}
			if [ $win -gt $DISK_SPACE_WARN_LEVEL ]; then
				win=$(urgent $win%)
			else 
				win=$win%
			fi
			raid=${sys_arr[3]}
			if [ $raid -gt $DISK_SPACE_WARN_LEVEL ]; then
				raid=$(urgent $raid%)
			else 
				raid=$raid%
			fi
			hdd="$PADDING$ICON_ROOT $root  $ICON_WIN $win  $ICON_RAID $raid$PADDING"

			########
			#NETWORK
			netdown=${sys_arr[5]}
			netup=${sys_arr[6]}
			#down=$(echo $down | numfmt --to=iec-i)
			#up=$(echo $up | numfmt --to=iec-i)
			netusage="$PADDING$netdown $ICON_NETUPDOWN $netup$PADDING"
			;;

		P*)
			# power
			power="%{A3:halt:}$PADDING${line#?}$PADDING%{A}"
			;;

		R*)
			# reboot
			reboot="%{A3:reboot:}$PADDING${line#?}$PADDING%{A}"
			;;

		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			wm_arr=( $line )
			for i in ${!wm_arr[@]}; do
				name=${wm_arr[i]:1:2}
				case ${wm_arr[i]} in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{U-}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{U-}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{U-}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}%{U$COLOR_BACKGROUND}%{+u}%{A1:bspc desktop -f ^$i:}$PADDING${name}$PADDING%{A}%{-u}%{U-}%{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}%{A1:bspc desktop -f ^$i:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}%{+u}%{A1:bspc desktop -f ^$i:}$PADDING${name}$PADDING%{A}%{-u}%{B-}%{F-}"
						;;
				esac
			done
			;;
	esac
	#printf "%s\n" "%{T4}%{l}${wm_infos}%{T-}${title}%{c}${netusage}%{r}${playing}${hdd}${cpu}${systemp}${ram}${ip}${volume}${clock}${power}${reboot}"
	printf "%s\n" "%{T4}%{l}%{A4:bspc desktop -f next:}%{A5:bspc desktop -f prev:}${wm_infos}%{A}%{A}%{T-}${title}%{c}${netusage}%{r}${hdd}${cpu}${systemp}${ram}${updates}${ip}${volume}${clock}${power}${reboot}"
done
