#! /bin/sh

bspc config border_width        0
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d       
#bspc monitor -d 1 2 3 4 5 6

bspc rule -a chromium desktop=^1
#bspc rule -a xfce4-terminal desktop=^4
#bspc rule -a thunar desktop=^5
#bspc rule -a subl3 desktop=^3
bspc rule -a Vlc desktop=^2
bspc rule -a Brackets desktop=^3
bspc rule -a Messengerfordesktop desktop=^6
bspc rule -a Hexchat desktop=^6
bspc rule -a Ristretto state=floating
bspc rule -a File-roller state=floating
bspc rule -a Keepassx state=floating
bspc rule -a Oblogout state=fullscreen
bspc rule -a Owncloud floating=off desktop=^7
bspc rule -a crx_fpniocchabmgenibceglhnfeimmdhdfm desktop=^2

# Lemonbar
/home/admin/.bar/panel &
